tomcat:
  container_name: mindmath0
  image: tomcat:9.0
  volumes:
         - ./build/libs/:/usr/local/tomcat/webapps/
  ports:
        - 8080:8080
  links:
         - cache
  restart: unless-stopped

cache:
   container_name: cache
   image: redis:latest
   volumes:
         - ./build/redis/:/data/
   expose:
         - 6379
   entrypoint: redis-server --appendonly yes
   restart: unless-stopped
